name: aqueduct_angular
description: An example of an Angular client talking to an Aqueduct server
version: 0.0.1
author: Clément Moyroud <clement.moyourd@gmail.com>

environment:
  sdk: '>=1.20.0 <2.0.0'
dependencies:
  aqueduct: any 
  angular2: ^2.0.0
  mime: any
  path: any
dev_dependencies:
  test: any
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    - 'package:angular2/common.dart#FORM_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
- $dart2js:
    commandLineOptions: [--show-package-warnings, --dump-info]
- dart_to_js_script_rewriter